version: '3.3'
services:
  app-go:
    container_name: app-go
    build:
      context: ./go
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${PWD}/go/src:/app
    ports:
      - "8080:8080"
    networks:
      - ctf-network
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - ctf-network
networks:
  ctf-network:
